## Prerequisites

Before running this notebook:

1. Authenticate with Databricks:
```bash
databricks auth login
```

2. Prepare the data:
```bash
uv run --group databricks python -m integration.databricks.prepare_jaffle_shop_data_for_databricks
```

This will load raw data from GCS and create the weekly sales forecasting population table.

## Setup and Data Loading

In [ ]:
from pathlib import Path

import getml
from databricks.connect import DatabricksSession

PROJECT_NAME = "databricks_feature_store"

getml.set_project(PROJECT_NAME)

  Loading pipelines...                     ━━━━━━━━━━━━━━━ 100% • 00:00

Connected to project 'databricks_feature_store'.

In [33]:
spark = DatabricksSession.builder.serverless().getOrCreate()

In [ ]:
# Load population table
weekly_sales_by_store_spark = spark.table(
    "workspace.prepared.weekly_sales_by_store_with_target"
)

weekly_sales_by_store = getml.DataFrame.from_arrow(
    weekly_sales_by_store_spark.toArrow(), name="weekly_sales_by_store"
)

# Load peripheral table
orders_spark = spark.table("workspace.raw.raw_orders")
orders = getml.DataFrame.from_arrow(orders_spark.toArrow(), name="orders")

/Users/awais/code17/projects/getML/github/getml-demo/.venv/lib/python3.12/site-packages/getml/data/_io/arrow.py:371: UserWarning:
Column 'next_week_sales' has been converted from decimal to float. This may
    result in a loss of precision!

  warnings.warn(

## getML Annotations

In [5]:
weekly_sales_by_store.set_role(
    cols=["store_id", "snapshot_id"], role=getml.data.roles.join_key
)
weekly_sales_by_store.set_role(cols="reference_date", role=getml.data.roles.time_stamp)
weekly_sales_by_store.set_role(cols="next_week_sales", role=getml.data.roles.target)
weekly_sales_by_store.set_role(
    cols=[
        "store_name",
        "year",
        "month",
        "week_number",
        "is_full_week_after_opening",
        "has_order_activity",
        "has_min_history",
    ],
    role=getml.data.roles.categorical,
)
weekly_sales_by_store.set_role(
    cols=["days_since_open", "next_week_orders"], role=getml.data.roles.numerical
)
weekly_sales_by_store

/Users/awais/code17/projects/getML/github/getml-demo/.venv/lib/python3.12/site-packages/getml/data/_io/arrow.py:393: UserWarning:
Column 'reference_date' has UTC timezone. Dropping the timezone.

    Currently, getML doesn't support the handling of explicit timezones for
timestamps. If you need timezone information to be available for your models, you
can encode the timezone explicitly in a separate column.

  warnings.warn(

name                reference_date                           store_id   snapshot_id   next_week_sales   ...
role                    time_stamp                           join_key      join_key            target   ...
unit   time stamp, comparison only                                                                      ...
   0                    2022-09-19   eafbd328-0434-4f46-9c2d-cc97a46f...           778          26020.74   ...
   1                    2023-10-16   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1115          19807.07   ...
   2                    2024-07-15   eafbd328-0434-4f46-9c2d-cc97a46f...          1348          21198.29   ...
   3                    2023-08-14   eafbd328-0434-4f46-9c2d-cc97a46f...          1060          20418.27   ...
   4                    2020-01-27   eafbd328-0434-4f46-9c2d-cc97a46f...           119          25682.76   ...
                               ...                                ...           ...             ...
1374                    2022-08-29   abfcc332-1eaf-42f6-b8e4-569bf6a3...           758          18024.09   ...
1375                    2024-04-08   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1265          18632.58   ...
1376                    2022-03-28   abfcc332-1eaf-42f6-b8e4-569bf6a3...           626          23063.98   ...
1377                    2022-08-01   abfcc332-1eaf-42f6-b8e4-569bf6a3...           734          18610.37   ...
1378                    2022-11-28   abfcc332-1eaf-42f6-b8e4-569bf6a3...           836          25652.78   ...

name   is_full_week_after_opening   has_order_activity   has_min_history   days_since_open   next_week_orders
role   categorical                  categorical          categorical             numerical          numerical
unit
   0   true                         true                 true                         1287               2389
   1   true                         true                 true                         1871               1627
   2   true                         true                 true                         1952               2066
   3   true                         true                 true                         1616               2054
   4   true                         true                 true                          321               2382
       ...                          ...                  ...                           ...                ...
1374   true                         true                 true                          853               1685
1375   true                         true                 true                         2046               1589
1376   true                         true                 true                          699               2093
1377   true                         true                 true                          825               1704
1378   true                         true                 true                          944               2221


1379 rows x 13 columns
memory usage: 0.09 MB
type: getml.DataFrame

In [6]:
orders.set_role(cols=["store_id", "id", "customer"], role=getml.data.roles.join_key)
orders.set_role(
    cols="ordered_at",
    role=getml.data.roles.time_stamp,
    time_formats=["%Y-%m-%dT%H:%M:%S"],
)
orders.set_role(
    cols=["subtotal", "order_total", "tax_paid"], role=getml.data.roles.numerical
)
orders

   name                    ordered_at                           store_id                                 id
   role                    time_stamp                           join_key                           join_key
   unit   time stamp, comparison only
      0           2018-09-01 09:07:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   2dfe5624-4340-4ae0-af9f-01edf04c...
      1           2018-09-01 08:32:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   80c27a4c-7d23-49fe-864e-1859a166...
      2           2018-09-01 13:00:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   bd7d415c-a44e-47ba-bf35-727ecf8b...
      3           2018-09-01 11:14:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   ed02759f-4d40-44c5-8583-2eddaf1e...
      4           2018-09-01 12:49:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   ff48d20e-7294-4ca1-9baa-85821bda...
                                  ...                                ...                                ...
2309598           2024-08-29 13:01:00   61743c9b-2394-4d36-8062-8a6820fa...   479b3bbd-170c-4fe6-9b83-19e9dd15...
2309599           2024-08-29 10:27:00   61743c9b-2394-4d36-8062-8a6820fa...   8e1feeb5-b8a6-47fc-8432-f8b7aea3...
2309600           2024-08-29 08:56:00   61743c9b-2394-4d36-8062-8a6820fa...   919345f8-0577-4d73-a191-06a29216...
2309601           2024-08-29 08:01:00   61743c9b-2394-4d36-8062-8a6820fa...   6ca68a2c-b962-4e81-9f82-3f347cc3...
2309602           2024-08-29 11:20:00   61743c9b-2394-4d36-8062-8a6820fa...   1b56cdd3-345d-488f-9a4a-6c4322b6...

   name                           customer    subtotal   order_total    tax_paid
   role                           join_key   numerical     numerical   numerical
   unit
      0   304f8066-3937-42ab-9edc-5e2c937e...        4000          4240         240
      1   ab45b9b0-e8cb-4eed-b1c7-5b3a70cd...         500           530          30
      2   530d100f-15de-49ea-93bb-28b570a7...        3200          3392         192
      3   5603ee30-171b-4f23-a0b3-3b4cd282...        5300          5618         318
      4   5512b3a7-632d-4daa-94a3-d24533fc...         600           636          36
                                       ...         ...           ...         ...
2309598   6ab94c27-8718-4907-854b-c8a4892e...         400           432          32
2309599   a866ff38-808f-458d-9c15-bb87b383...         600           648          48
2309600   34f910be-3d58-41e6-9d68-0f07789f...         400           432          32
2309601   78ab9d2c-dcd4-4b5e-a4d9-d4a86633...         400           432          32
2309602   f54357ad-5473-4601-ad54-8d3a758d...        1100          1188          88


2309603 rows x 7 columns
memory usage: 101.62 MB
type: getml.DataFrame

## getML Data Model

In [8]:
validation_begin = getml.data.time.datetime(2023, 1, 1)
test_begin = getml.data.time.datetime(2024, 1, 1)

split = getml.data.split.time(
    population=weekly_sales_by_store,
    time_stamp="reference_date",
    validation=validation_begin,
    test=test_begin,
)

# Filter dataframes using the split column
weekly_sales_by_store_train = weekly_sales_by_store[split == "train"]
weekly_sales_by_store_validation = weekly_sales_by_store[split == "validation"]
weekly_sales_by_store_test = weekly_sales_by_store[split == "test"]

print(
    f"Training set size: {len(weekly_sales_by_store_train)}"
    f"\nValidation set size: {len(weekly_sales_by_store_validation)}"
    f"\nTest set size: {len(weekly_sales_by_store_test)}"
)

Training set size: 863
Validation set size: 312
Test set size: 204

In [38]:
data_model = getml.data.DataModel(
    population=weekly_sales_by_store_train.to_placeholder("weekly_sales_by_store")
)

# Add all peripheral tables
data_model.add(
    getml.data.to_placeholder(
        orders=orders,
    )
)

# Define relationships using joins
data_model.weekly_sales_by_store.join(
    right=data_model.orders,
    on="store_id",
    time_stamps=("reference_date", "ordered_at"),
    relationship=getml.data.relationship.one_to_many,
    memory=getml.data.time.days(30),
)

In [ ]:
container = getml.data.Container(
    train=weekly_sales_by_store_train,
    validation=weekly_sales_by_store_validation,
    test=weekly_sales_by_store_test,
)

# Add peripheral tables with aliases matching the data model placeholders
container.add(
    orders=orders,
)

getml.project.data_frames.save()
container.save()

In [40]:
container._id

'uzNVUz'

## Training

In [9]:
fast_prop = getml.feature_learning.FastProp()

predictor = getml.predictors.XGBoostRegressor(
    n_jobs=0,
)

pipe = getml.Pipeline(
    data_model=data_model,
    feature_learners=[
        fast_prop,
    ],
    predictors=[predictor],
)

pipe.fit(container.train)
pipe.score(container.test)

Checking data model...

  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Checking...                              ━━━━━━━━━━━━━━━ 100% • 00:00

The pipeline check generated 0 issues labeled INFO and 2 issues labeled WARNING.

To see the issues in full, run .check() on the pipeline.

  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:01
  FastProp: Trying 50 features...          ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:02
  XGBoost: Training as predictor...        ━━━━━━━━━━━━━━━ 100% • 00:02

Trained pipeline.

Time taken: 0:00:06.494403.

  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:01

    date time             set used   target                  mae        rmse   rsquared
0   2026-01-06 15:39:45   train      next_week_sales    249.6961    319.0279     0.9973
1   2026-01-06 15:39:49   test       next_week_sales    472.4813    613.3892     0.9862

In [ ]:
# container = getml.data.load_container("uzNVUz")
# pipe = getml.pipeline.load("2aj2Dm")

## Feature Export

In [13]:
# Transform features using getML pipeline
features_df = pipe.transform(
    population_table=weekly_sales_by_store,
    peripheral_tables=[orders],
    df_name="features",
)


features_spark = spark.createDataFrame(features_df.to_arrow())

features_df

  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00

name                reference_date                           store_id   snapshot_id   next_week_sales   ...   feature_1_48
role                    time_stamp                           join_key      join_key            target   ...      numerical
unit   time stamp, comparison only                                                                      ...
   0                    2022-09-19   eafbd328-0434-4f46-9c2d-cc97a46f...           778          26020.74   ...              0
   1                    2023-10-16   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1115          19807.07   ...              0
   2                    2024-07-15   eafbd328-0434-4f46-9c2d-cc97a46f...          1348          21198.29   ...              0
   3                    2023-08-14   eafbd328-0434-4f46-9c2d-cc97a46f...          1060          20418.27   ...              0
   4                    2020-01-27   eafbd328-0434-4f46-9c2d-cc97a46f...           119          25682.76   ...              0
                               ...                                ...           ...             ...                    ...
1374                    2022-08-29   abfcc332-1eaf-42f6-b8e4-569bf6a3...           758          18024.09   ...              0
1375                    2024-04-08   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1265          18632.58   ...              0
1376                    2022-03-28   abfcc332-1eaf-42f6-b8e4-569bf6a3...           626          23063.98   ...              0
1377                    2022-08-01   abfcc332-1eaf-42f6-b8e4-569bf6a3...           734          18610.37   ...              0
1378                    2022-11-28   abfcc332-1eaf-42f6-b8e4-569bf6a3...           836          25652.78   ...              0

name   feature_1_49   feature_1_50   days_since_open   next_week_orders
role      numerical      numerical         numerical          numerical
unit
   0       305.7557           8278              1287               2389
   1       398.29             6352              1871               1627
   2       283.4024           8930              1952               2066
   3       299.0779           8460              1616               2054
   4       267.0307           9468               321               2382
            ...                ...               ...                ...
1374       358.8599           7053               853               1685
1375       378.6294           6684              2046               1589
1376       285.4297           8867               699               2093
1377       362.3368           6985               825               1704
1378       273.7285           9246               944               2221


1379 rows x 56 columns
memory usage: 0.61 MB
type: getml.DataFrame

In [28]:
from getml_interpretations import (
    ColumnDescriptionsReport,
    generate_column_descriptions_report,
)

column_descriptions_report_path = Path("column_descriptions_report.json")
jaffle_shop_annotations = Path("annotations.yml")
user_prompt = f"""
Please use the following annotations as source of truth for generating the
column descriptions report:

{jaffle_shop_annotations.read_text()}.
"""

if column_descriptions_report_path.exists():
    column_descriptions_report = ColumnDescriptionsReport.from_json(
        column_descriptions_report_path
    )
else:
    column_descriptions_report: ColumnDescriptionsReport = (
        await generate_column_descriptions_report(
            project_name=PROJECT_NAME,
            pipeline=pipe,
            container=container,
            model="gpt-5-mini",
            user_prompt=user_prompt,
        )
    )
    column_descriptions_report.to_json(column_descriptions_report_path)

In [15]:
from pathlib import Path

from getml_interpretations import (
    FeatureDescriptionsReport,
    generate_feature_descriptions_report,
)

feature_descriptions_report_path = Path("feature_descriptions_report.json")

user_prompt = """
Feature descriptions are limited to max. 256 characters and 2-3 sentences.
Please ensure that each feature description does not exceed this limit.
Also no bullet points, new lines or line breaks etc.
Keep the descriptions concise, straight-forward and informative.
"""

if feature_descriptions_report_path.exists():
    feature_descriptions_report = FeatureDescriptionsReport.from_json(
        feature_descriptions_report_path
    )
else:
    feature_descriptions_report: FeatureDescriptionsReport = (
        await generate_feature_descriptions_report(
            project_name=PROJECT_NAME,
            pipeline=pipe,
            container=container,
            user_prompt=user_prompt,
            model="gpt-5-mini",
            batch_size=20,
        )
    )
    feature_descriptions_report.to_json(feature_descriptions_report_path)

In [ ]:
column_mapping = {
    desc.name: desc.title
    for desc in feature_descriptions_report.feature_descriptions.values()
}

for old_name, new_name in column_mapping.items():
    features_spark = features_spark.withColumnRenamed(old_name, new_name)

In [24]:
FEATURES_TABLE_FULL_NAME = "workspace.getml_fs.getml_features_explained"
spark.sql(f"DROP TABLE IF EXISTS {FEATURES_TABLE_FULL_NAME}")

features_spark.write.format("delta").mode("overwrite").option(
    "overwriteSchema", "true"
).saveAsTable(FEATURES_TABLE_FULL_NAME)

spark.sql(f"""
    ALTER TABLE {FEATURES_TABLE_FULL_NAME}
    ALTER COLUMN snapshot_id SET NOT NULL
""")

FEATURES_TABLE_NAME = FEATURES_TABLE_FULL_NAME.split(".")[-1]

spark.sql(f"""
    ALTER TABLE {FEATURES_TABLE_FULL_NAME}
    ADD CONSTRAINT {FEATURES_TABLE_NAME}_pk PRIMARY KEY(snapshot_id)
""")

DataFrame[]

In [39]:
for tables in column_descriptions_report.column_descriptions.values():
    for column_name, column_description in tables.items():
        if column_name in features_df.colnames:
            # Escape single quotes to prevent SQL syntax errors
            description = column_description.description.replace("'", "\\'")
            spark.sql(
                f"ALTER TABLE {FEATURES_TABLE_FULL_NAME} CHANGE COLUMN {column_name} COMMENT '{description}'"
            )

Updating description for column: reference_date
Updating description for column: store_id
Updating description for column: snapshot_id
Updating description for column: next_week_sales
Updating description for column: days_since_open
Updating description for column: next_week_orders
Updating description for column: store_id

In [34]:
for feature_description in feature_descriptions_report.feature_descriptions.values():
    # Escape single quotes to prevent SQL syntax errors
    description = feature_description.description.replace("'", "\\'")
    spark.sql(
        f"ALTER TABLE {FEATURES_TABLE_FULL_NAME} CHANGE COLUMN {feature_description.title} COMMENT '{description}'"
    )

In [19]:
# Verify the Feature Table was created
print("Table schema:")
spark.sql(f"DESCRIBE TABLE {FEATURES_TABLE_FULL_NAME}").show(100, truncate=False)

Table schema:
+-------------------------------+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|col_name                       |data_type|comment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+-------------------------------+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|store_id                       |string   |NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|snapshot_id                    |string   |NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|avg_subtotal_30d               |double   |Computes the average order subtotal across all transactions for the same store observed up to the snapshot date, restricted to the recent 30‑day memory window. Implemented by joining transaction rows on store identifier and averaging the subtotal values for orders with ordered_at ≤ reference_date (and within the 30‑day truncation). Captures recent typical order size [monetary, e.g., USD?]; useful as a proxy for average basket value. Low correlation with the target in this model, so treat as a secondary signal and verify monetary units and scaling before use.                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|distinct_subtotal_count_30d    |double   |Counts the number of distinct subtotal amounts observed for the store in the 30‑day window prior to the snapshot. Built via a grouped join on store_id and distinct counting of the subtotal field for orders up to reference_date. Serves as a measure of heterogeneity in order sizes (higher counts indicate more variety in basket sizes) [count]. Shows modest positive correlation with the target here; consider as a diversity/variability indicator rather than a direct revenue estimate.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|duplicate_subtotal_count_30d   |double   |Measures how many order subtotals repeat by computing total order count minus distinct subtotal count within the 30‑day window. Derived from joined order rows for the store up to the snapshot date, it highlights frequency of repeated identical subtotals (e.g., common basket sizes or recurring order templates) [count]. Highly correlated with revenue-related aggregates in this dataset — may capture promotional or repeated-order behavior — but could be redundant with total/count features, so check multicollinearity before including in parsimonious models.                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|first_subtotal_30d             |double   |Selects the subtotal value of the earliest order in the 30‑day lookback (earliest ordered_at ≤ reference_date). Computed by joining orders to the snapshot and choosing the first subtotal by timestamp. Provides a simple recency-ordered snapshot of an older order within the window [monetary, e.g., USD?]; useful to detect shifts in basket size over the window when compared with the latest value. Low predictive contribution on its own in this model, but can be informative in combination with last/avg measures.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|last_subtotal_30d              |double   |Returns the subtotal of the most recent order before the snapshot within the 30‑day memory window (latest ordered_at ≤ reference_date). Obtained by joining transaction rows on store_id and selecting the value associated with the maximum timestamp. Acts as a short-term recency indicator of order size [monetary, e.g., USD?]; in this dataset it has a modest negative correlation with the target, so consider using alongside aggregates (sum/avg) to capture trend and recent shifts.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|max_subtotal_30d               |double   |Returns the maximum subtotal observed in the 30‑day window preceding the snapshot for the given store. Calculated by grouping joined orders (by store) and taking the maximum subtotal for orders with ordered_at ≤ reference_date. Captures occasional large baskets or outlier transactions [monetary, e.g., USD?]; can identify high-value events but may be sensitive to single outliers, so robustify (winsorize) or pair with median/stddev for stability.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|median_subtotal_30d            |double   |Computes the median subtotal among all orders for the store in the 30‑day lookback prior to the snapshot. Built from joined orders filtered by timestamp and grouped by snapshot row. Provides a robust central tendency of order size that is less influenced by outliers than the mean [monetary, e.g., USD?]. In cases with many identical small orders the median can be more stable and useful than mean-based signals.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|min_subtotal_30d               |double   |Returns the minimum observed subtotal among orders up to the snapshot within the 30‑day memory window. Computed by grouping joined transactions on store_id and taking the minimum subtotal where ordered_at ≤ reference_date. Indicates the floor of observed basket values [monetary, e.g., USD?]; often 0 for refunded or zero-value orders and so should be interpreted with caution (treat zeros separately if they indicate returns/cancellations).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|mode_subtotal_30d              |double   |Selects the most frequent subtotal value within the 30‑day window ending at the snapshot. Implemented by grouping orders for the store and returning the modal subtotal among orders with ordered_at ≤ reference_date. Useful to detect a common basket size (e.g., a menu item or standardized purchase) [monetary, e.g., USD?]; modal values can be informative for understanding typical transaction patterns but may be non-unique or unstable for small samples.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|stddev_subtotal_30d            |double   |Computes the standard deviation of order subtotals across the 30‑day lookback prior to the snapshot. Produced by aggregating joined order rows for the store and calculating sample dispersion of the subtotal field for orders with ordered_at ≤ reference_date. Captures variability in basket sizes [monetary dispersion]; negatively correlated with the target in this model, indicating that higher variability in subtotals within the window is associated with lower next‑week sales here — could reflect inconsistent demand or mixed transaction types.                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|sum_subtotal_30d               |double   |Sums all order subtotals for the store within the 30‑day window leading up to the snapshot (orders with ordered_at ≤ reference_date). Implemented via a grouped join on store_id and summation of the subtotal field. Acts as a recent-revenue proxy over the month‑to‑date period [monetary, e.g., USD?] and is highly correlated with the target in this dataset — one of the stronger historical revenue signals. Validate units/scaling and beware redundancy with other sum/count features.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|trend_subtotal_30d             |double   |Estimates a trend coefficient of subtotal values versus recency by regressing subtotal on time‑difference (reference_date − ordered_at) within the 30‑day window. Computed using a trend aggregation on joined orders for the store and captures whether average basket sizes are increasing or decreasing as orders approach the snapshot [trend in monetary units per time]. Use to detect momentum in order value; implementation specifics of the TREND operator (slope units and normalization) should be reviewed before interpretation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|avg_order_total_30d            |double   |Calculates the average full order amount (order_total) for transactions in the 30‑day lookback prior to the snapshot. Built by joining orders on store_id and averaging order_total for orders with ordered_at ≤ reference_date. Serves as an AOV-style indicator that includes taxes/fees [monetary, e.g., USD?]; can complement subtotal-based signals where fees or rounding matter. Has modest predictive value and should be checked for unit consistency.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|distinct_order_total_count_30d |double   |Counts distinct values of the full order amount (order_total) observed for the store in the 30‑day window preceding the snapshot. Computed via grouped join and distinct counting of order_total for orders ≤ reference_date. Indicates variability in final charged amounts (including taxes/fees) [count]; useful as a complement to subtotal distinct counts to detect pricing or fee heterogeneity.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |