## Prerequisites

Before running this notebook:

1. Authenticate with Databricks:
```bash
databricks auth login
```

2. Prepare the data:
```bash
uv run --group databricks python -m integration.databricks.prepare_jaffle_shop_data_for_databricks
```

This will load raw data from GCS and create the weekly sales forecasting population table.

## Setup and Data Loading

In [2]:
import getml
from databricks.connect import DatabricksSession

getml.set_project("databricks_feature_store")

  Loading pipelines... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00

Connected to project 'databricks_feature_store'.

In [3]:
spark = DatabricksSession.builder.serverless().getOrCreate()

In [4]:
weekly_sales_by_store_spark = spark.table(
    "workspace.prepared.weekly_sales_by_store_with_target"
)

weekly_sales_by_store = getml.DataFrame.from_arrow(
    weekly_sales_by_store_spark.toArrow(), name="weekly_sales_by_store"
)

# # Load orders table
orders_spark = spark.table("workspace.raw.raw_orders")
orders = getml.DataFrame.from_arrow(orders_spark.toArrow(), name="orders")

/Users/awais/code17/projects/getML/github/getml-demo/.venv/lib/python3.12/site-packages/getml/data/_io/arrow.py:326: UserWarning:
Column 'next_week_sales' has been converted from decimal to float. This may
    result in a loss of precision!

  warnings.warn(

## getML Annotations

In [5]:
weekly_sales_by_store.set_role(
    cols=["store_id", "snapshot_id"], role=getml.data.roles.join_key
)
weekly_sales_by_store.set_role(cols="reference_date", role=getml.data.roles.time_stamp)
weekly_sales_by_store.set_role(cols="next_week_sales", role=getml.data.roles.target)
weekly_sales_by_store.set_role(
    cols=[
        "store_name",
        "year",
        "month",
        "week_number",
        "is_full_week_after_opening",
        "has_order_activity",
        "has_min_history",
    ],
    role=getml.data.roles.categorical,
)
weekly_sales_by_store.set_role(
    cols=["days_since_open", "next_week_orders"], role=getml.data.roles.numerical
)
weekly_sales_by_store

/Users/awais/code17/projects/getML/github/getml-demo/.venv/lib/python3.12/site-packages/getml/data/_io/arrow.py:348: UserWarning:
Column 'reference_date' has UTC timezone. Dropping the timezone.

    Currently, getML doesn't support the handling of explicit timezones for
timestamps. If you need timezone information to be available for your models, you
can encode the timezone explicitly in a separate column.

  warnings.warn(

name                reference_date                           store_id   snapshot_id   next_week_sales   ...
role                    time_stamp                           join_key      join_key            target   ...
unit   time stamp, comparison only                                                                      ...
   0                    2022-09-19   eafbd328-0434-4f46-9c2d-cc97a46f...           778          26020.74   ...
   1                    2023-10-16   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1115          19807.07   ...
   2                    2024-07-15   eafbd328-0434-4f46-9c2d-cc97a46f...          1348          21198.29   ...
   3                    2023-08-14   eafbd328-0434-4f46-9c2d-cc97a46f...          1060          20418.27   ...
   4                    2020-01-27   eafbd328-0434-4f46-9c2d-cc97a46f...           119          25682.76   ...
                               ...                                ...           ...             ...
1374                    2022-08-29   abfcc332-1eaf-42f6-b8e4-569bf6a3...           758          18024.09   ...
1375                    2024-04-08   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1265          18632.58   ...
1376                    2022-03-28   abfcc332-1eaf-42f6-b8e4-569bf6a3...           626          23063.98   ...
1377                    2022-08-01   abfcc332-1eaf-42f6-b8e4-569bf6a3...           734          18610.37   ...
1378                    2022-11-28   abfcc332-1eaf-42f6-b8e4-569bf6a3...           836          25652.78   ...

name   is_full_week_after_opening   has_order_activity   has_min_history   days_since_open   next_week_orders
role   categorical                  categorical          categorical             numerical          numerical
unit
   0   true                         true                 true                         1287               2389
   1   true                         true                 true                         1871               1627
   2   true                         true                 true                         1952               2066
   3   true                         true                 true                         1616               2054
   4   true                         true                 true                          321               2382
       ...                          ...                  ...                           ...                ...
1374   true                         true                 true                          853               1685
1375   true                         true                 true                         2046               1589
1376   true                         true                 true                          699               2093
1377   true                         true                 true                          825               1704
1378   true                         true                 true                          944               2221


1379 rows x 13 columns
memory usage: 0.09 MB
type: getml.DataFrame

In [6]:
orders.set_role(cols=["store_id", "id", "customer"], role=getml.data.roles.join_key)
orders.set_role(
    cols="ordered_at",
    role=getml.data.roles.time_stamp,
    time_formats=["%Y-%m-%dT%H:%M:%S"],
)
orders.set_role(
    cols=["subtotal", "order_total", "tax_paid"], role=getml.data.roles.numerical
)
orders

   name                    ordered_at                           store_id                                 id
   role                    time_stamp                           join_key                           join_key
   unit   time stamp, comparison only
      0           2018-09-01 09:07:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   2dfe5624-4340-4ae0-af9f-01edf04c...
      1           2018-09-01 08:32:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   80c27a4c-7d23-49fe-864e-1859a166...
      2           2018-09-01 13:00:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   bd7d415c-a44e-47ba-bf35-727ecf8b...
      3           2018-09-01 11:14:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   ed02759f-4d40-44c5-8583-2eddaf1e...
      4           2018-09-01 12:49:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   ff48d20e-7294-4ca1-9baa-85821bda...
                                  ...                                ...                                ...
2309598           2024-08-29 13:01:00   61743c9b-2394-4d36-8062-8a6820fa...   479b3bbd-170c-4fe6-9b83-19e9dd15...
2309599           2024-08-29 10:27:00   61743c9b-2394-4d36-8062-8a6820fa...   8e1feeb5-b8a6-47fc-8432-f8b7aea3...
2309600           2024-08-29 08:56:00   61743c9b-2394-4d36-8062-8a6820fa...   919345f8-0577-4d73-a191-06a29216...
2309601           2024-08-29 08:01:00   61743c9b-2394-4d36-8062-8a6820fa...   6ca68a2c-b962-4e81-9f82-3f347cc3...
2309602           2024-08-29 11:20:00   61743c9b-2394-4d36-8062-8a6820fa...   1b56cdd3-345d-488f-9a4a-6c4322b6...

   name                           customer    subtotal   order_total    tax_paid
   role                           join_key   numerical     numerical   numerical
   unit
      0   304f8066-3937-42ab-9edc-5e2c937e...        4000          4240         240
      1   ab45b9b0-e8cb-4eed-b1c7-5b3a70cd...         500           530          30
      2   530d100f-15de-49ea-93bb-28b570a7...        3200          3392         192
      3   5603ee30-171b-4f23-a0b3-3b4cd282...        5300          5618         318
      4   5512b3a7-632d-4daa-94a3-d24533fc...         600           636          36
                                       ...         ...           ...         ...
2309598   6ab94c27-8718-4907-854b-c8a4892e...         400           432          32
2309599   a866ff38-808f-458d-9c15-bb87b383...         600           648          48
2309600   34f910be-3d58-41e6-9d68-0f07789f...         400           432          32
2309601   78ab9d2c-dcd4-4b5e-a4d9-d4a86633...         400           432          32
2309602   f54357ad-5473-4601-ad54-8d3a758d...        1100          1188          88


2309603 rows x 7 columns
memory usage: 101.62 MB
type: getml.DataFrame

## getML Data Model

In [61]:
validation_begin = getml.data.time.datetime(2023, 1, 1)
test_begin = getml.data.time.datetime(2024, 1, 1)

split = getml.data.split.time(
    population=weekly_sales_by_store,
    time_stamp="reference_date",
    validation=validation_begin,
    test=test_begin,
)

# Filter dataframes using the split column
weekly_sales_by_store_train = weekly_sales_by_store[split == "train"]
weekly_sales_by_store_validation = weekly_sales_by_store[split == "validation"]
weekly_sales_by_store_test = weekly_sales_by_store[split == "test"]

print(
    f"Training set size: {len(weekly_sales_by_store_train)}"
    f"\nValidation set size: {len(weekly_sales_by_store_validation)}"
    f"\nTest set size: {len(weekly_sales_by_store_test)}"
)

Training set size: 863
Validation set size: 312
Test set size: 204

In [62]:
data_model = getml.data.DataModel(
    population=weekly_sales_by_store_train.to_placeholder("weekly_sales_by_store")
)

# Add all peripheral tables
data_model.add(
    getml.data.to_placeholder(
        orders=orders,
    )
)

# Define relationships using joins
data_model.weekly_sales_by_store.join(
    right=data_model.orders,
    on="store_id",
    time_stamps=("reference_date", "ordered_at"),
    relationship=getml.data.relationship.one_to_many,
    memory=getml.data.time.days(30),
)

In [63]:
container = getml.data.Container(
    train=weekly_sales_by_store_train,
    validation=weekly_sales_by_store_validation,
    test=weekly_sales_by_store_test,
)

# Add peripheral tables with aliases matching the data model placeholders
container.add(
    orders=orders,
)
# container.save()
# getml.project.data_frames.save()

## Training

In [64]:
fast_prop = getml.feature_learning.FastProp()

predictor = getml.predictors.XGBoostRegressor(
    n_jobs=0,
)

pipe = getml.Pipeline(
    data_model=data_model,
    feature_learners=[
        fast_prop,
    ],
    predictors=[predictor],
)

pipe.fit(container.train)

Checking data model...

  Staging... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  Checking... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00

The pipeline check generated 0 issues labeled INFO and 2 issues labeled WARNING.

To see the issues in full, run .check() on the pipeline.

  Staging... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Trying 50 features... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:02
  XGBoost: Training as predictor... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:02

Trained pipeline.

Time taken: 0:00:05.661075.

Pipeline(data_model='weekly_sales_by_store',
         feature_learners=['FastProp'],
         feature_selectors=[],
         include_categorical=False,
         loss_function='SquareLoss',
         peripheral=['orders'],
         predictors=['XGBoostRegressor'],
         preprocessors=[],
         share_selected_features=0.5,
         tags=['container-NQBpU0'])

In [ ]:
# predictions = pipe.predict(container.test)

# # Calculate metrics
# scores = pipe.score(container.test)
# scores

  Staging... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:03
  Staging... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:03

    date time             set used   target                  mae        rmse   rsquared
0   2025-12-16 08:08:11   train      next_week_sales    249.6961    319.0279     0.9973
1   2025-12-16 08:08:23   test       next_week_sales    470.8753    613.0891     0.9862

In [7]:
pipe = getml.pipeline.load("CzNABb")

## Feature Export

In [ ]:
# Transform features using getML pipeline
features_df = pipe.transform(
    population_table=weekly_sales_by_store,
    peripheral_tables=[orders],
    df_name="features",
)


features_spark = spark.createDataFrame(features_df.to_arrow())

features_df

  Staging... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 00:00

name                reference_date                           store_id   snapshot_id   next_week_sales   ...   feature_1_48
role                    time_stamp                           join_key      join_key            target   ...      numerical
unit   time stamp, comparison only                                                                      ...
   0                    2022-09-19   eafbd328-0434-4f46-9c2d-cc97a46f...           778          26020.74   ...              0
   1                    2023-10-16   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1115          19807.07   ...              0
   2                    2024-07-15   eafbd328-0434-4f46-9c2d-cc97a46f...          1348          21198.29   ...              0
   3                    2023-08-14   eafbd328-0434-4f46-9c2d-cc97a46f...          1060          20418.27   ...              0
   4                    2020-01-27   eafbd328-0434-4f46-9c2d-cc97a46f...           119          25682.76   ...              0
                               ...                                ...           ...             ...                    ...
1374                    2022-08-29   abfcc332-1eaf-42f6-b8e4-569bf6a3...           758          18024.09   ...              0
1375                    2024-04-08   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1265          18632.58   ...              0
1376                    2022-03-28   abfcc332-1eaf-42f6-b8e4-569bf6a3...           626          23063.98   ...              0
1377                    2022-08-01   abfcc332-1eaf-42f6-b8e4-569bf6a3...           734          18610.37   ...              0
1378                    2022-11-28   abfcc332-1eaf-42f6-b8e4-569bf6a3...           836          25652.78   ...              0

name   feature_1_49   feature_1_50   days_since_open   next_week_orders
role      numerical      numerical         numerical          numerical
unit
   0       305.7557           8278              1287               2389
   1       398.29             6352              1871               1627
   2       283.4024           8930              1952               2066
   3       299.0779           8460              1616               2054
   4       267.0307           9468               321               2382
            ...                ...               ...                ...
1374       358.8599           7053               853               1685
1375       378.6294           6684              2046               1589
1376       285.4297           8867               699               2093
1377       362.3368           6985               825               1704
1378       273.7285           9246               944               2221


1379 rows x 56 columns
memory usage: 0.61 MB
type: getml.DataFrame

In [10]:
spark.sql("DROP TABLE IF EXISTS workspace.getml_fs.getml_features")

features_spark.write.format("delta").mode("overwrite").option(
    "overwriteSchema", "true"
).saveAsTable("workspace.getml_fs.getml_features")

spark.sql("""
    ALTER TABLE workspace.getml_fs.getml_features
    ALTER COLUMN snapshot_id SET NOT NULL
""")

spark.sql("""
    ALTER TABLE workspace.getml_fs.getml_features
    ADD CONSTRAINT getml_features_pk PRIMARY KEY(snapshot_id)
""")

DataFrame[]

In [11]:
for feature in pipe.features:
    spark.sql(
        f"ALTER TABLE workspace.getml_fs.getml_features CHANGE COLUMN {feature.name} COMMENT '{feature.sql}'"
    )

In [ ]:
# Verify the Feature Table was created
print("Table schema:")
spark.sql("DESCRIBE TABLE workspace.getml_fs.getml_features").show(100, truncate=False)

Table schema:
+----------------+---------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|col_name        |data_type|comment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+----------------+---------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|store_id        |string   |NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|snapshot_id     |string   |NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|feature_1_1     |double   |DROP TABLE IF EXISTS "FEATURE_1_1";\n\nCREATE TABLE "FEATURE_1_1" AS\nSELECT MIN( t2."subtotal" ) AS "feature_1_1",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                                  |
|feature_1_2     |double   |DROP TABLE IF EXISTS "FEATURE_1_2";\n\nCREATE TABLE "FEATURE_1_2" AS\nSELECT SUM( t2."subtotal" ) AS "feature_1_2",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                                  |
|feature_1_3     |double   |DROP TABLE IF EXISTS "FEATURE_1_3";\n\nCREATE TABLE "FEATURE_1_3" AS\nSELECT COUNT( DISTINCT t2."subtotal" ) AS "feature_1_3",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                       |
|feature_1_4     |double   |DROP TABLE IF EXISTS "FEATURE_1_4";\n\nCREATE TABLE "FEATURE_1_4" AS\nSELECT STDDEV( t2."subtotal" ) AS "feature_1_4",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                               |
|feature_1_5     |double   |DROP TABLE IF EXISTS "FEATURE_1_5";\n\nCREATE TABLE "FEATURE_1_5" AS\nSELECT FIRST( t2."subtotal", t2."ordered_at" ) AS "feature_1_5",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                               |
|feature_1_6     |double   |DROP TABLE IF EXISTS "FEATURE_1_6";\n\nCREATE TABLE "FEATURE_1_6" AS\nSELECT MEDIAN( t2."subtotal" ) AS "feature_1_6",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                               |
|feature_1_7     |double   |DROP TABLE IF EXISTS "FEATURE_1_7";\n\nCREATE TABLE "FEATURE_1_7" AS\nSELECT LAST( t2."subtotal", t2."ordered_at" ) AS "feature_1_7",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                |
|feature_1_8     |double   |DROP TABLE IF EXISTS "FEATURE_1_8";\n\nCREATE TABLE "FEATURE_1_8" AS\nSELECT MAX( t2."subtotal" ) AS "feature_1_8",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                                  |
|feature_1_9     |double   |DROP TABLE IF EXISTS "FEATURE_1_9";\n\nCREATE TABLE "FEATURE_1_9" AS\nSELECT AVG( t2."subtotal" ) AS "feature_1_9",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                                  |
|feature_1_10    |double   |DROP TABLE IF EXISTS "FEATURE_1_10";\n\nCREATE TABLE "FEATURE_1_10" AS\nSELECT MODE( t2."subtotal" ) AS "feature_1_10",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                              |
|feature_1_11    |double   |DROP TABLE IF EXISTS "FEATURE_1_11";\n\nCREATE TABLE "FEATURE_1_11" AS\nSELECT COUNT( t2."subtotal"  ) - COUNT( DISTINCT t2."subtotal" ) AS "feature_1_11",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                          |
|feature_1_12    |double   |DROP TABLE IF EXISTS "FEATURE_1_12";\n\nCREATE TABLE "FEATURE_1_12" AS\nSELECT TREND( t2."subtotal", t1."reference_date" - t2."ordered_at" ) AS "feature_1_12",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                      |
|feature_1_13    |double   |DROP TABLE IF EXISTS "FEATURE_1_13";\n\nCREATE TABLE "FEATURE_1_13" AS\nSELECT MIN( t2."order_total" ) AS "feature_1_13",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                            |
|feature_1_14    |double   |DROP TABLE IF EXISTS "FEATURE_1_14";\n\nCREATE TABLE "FEATURE_1_14" AS\nSELECT SUM( t2."order_total" ) AS "feature_1_14",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                            |
|feature_1_15    |double   |DROP TABLE IF EXISTS "FEATURE_1_15";\n\nCREATE TABLE "FEATURE_1_15" AS\nSELECT COUNT( DISTINCT t2."order_total" ) AS "feature_1_15",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                 |
|feature_1_16    |double   |DROP TABLE IF EXISTS "FEATURE_1_16";\n\nCREATE TABLE "FEATURE_1_16" AS\nSELECT STDDEV( t2."order_total" ) AS "feature_1_16",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                         |
|feature_1_17    |double   |DROP TABLE IF EXISTS "FEATURE_1_17";\n\nCREATE TABLE "FEATURE_1_17" AS\nSELECT FIRST( t2."order_total", t2."ordered_at" ) AS "feature_1_17",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                         |
|feature_1_18    |double   |DROP TABLE IF EXISTS "FEATURE_1_18";\n\nCREATE TABLE "FEATURE_1_18" AS\nSELECT MEDIAN( t2."order_total" ) AS "feature_1_18",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                         |
|feature_1_19    |double   |DROP TABLE IF EXISTS "FEATURE_1_19";\n\nCREATE TABLE "FEATURE_1_19" AS\nSELECT LAST( t2."order_total", t2."ordered_at" ) AS "feature_1_19",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                          |
|feature_1_20    |double   |DROP TABLE IF EXISTS "FEATURE_1_20";\n\nCREATE TABLE "FEATURE_1_20" AS\nSELECT MAX( t2."order_total" ) AS "feature_1_20",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                            |
|feature_1_21    |double   |DROP TABLE IF EXISTS "FEATURE_1_21";\n\nCREATE TABLE "FEATURE_1_21" AS\nSELECT AVG( t2."order_total" ) AS "feature_1_21",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                            |
|feature_1_22    |double   |DROP TABLE IF EXISTS "FEATURE_1_22";\n\nCREATE TABLE "FEATURE_1_22" AS\nSELECT MODE( t2."order_total" ) AS "feature_1_22",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                           |
|feature_1_23    |double   |DROP TABLE IF EXISTS "FEATURE_1_23";\n\nCREATE TABLE "FEATURE_1_23" AS\nSELECT COUNT( t2."order_total"  ) - COUNT( DISTINCT t2."order_total" ) AS "feature_1_23",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                    |
|feature_1_24    |double   |DROP TABLE IF EXISTS "FEATURE_1_24";\n\nCREATE TABLE "FEATURE_1_24" AS\nSELECT TREND( t2."order_total", t1."reference_date" - t2."ordered_at" ) AS "feature_1_24",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                   |
|feature_1_25    |double   |DROP TABLE IF EXISTS "FEATURE_1_25";\n\nCREATE TABLE "FEATURE_1_25" AS\nSELECT MIN( t2."tax_paid" ) AS "feature_1_25",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                               |
|feature_1_26    |double   |DROP TABLE IF EXISTS "FEATURE_1_26";\n\nCREATE TABLE "FEATURE_1_26" AS\nSELECT SUM( t2."tax_paid" ) AS "feature_1_26",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                               |
|feature_1_27    |double   |DROP TABLE IF EXISTS "FEATURE_1_27";\n\nCREATE TABLE "FEATURE_1_27" AS\nSELECT COUNT( DISTINCT t2."tax_paid" ) AS "feature_1_27",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                    |
|feature_1_28    |double   |DROP TABLE IF EXISTS "FEATURE_1_28";\n\nCREATE TABLE "FEATURE_1_28" AS\nSELECT STDDEV( t2."tax_paid" ) AS "feature_1_28",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                            |
|feature_1_29    |double   |DROP TABLE IF EXISTS "FEATURE_1_29";\n\nCREATE TABLE "FEATURE_1_29" AS\nSELECT FIRST( t2."tax_paid", t2."ordered_at" ) AS "feature_1_29",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                            |
|feature_1_30    |double   |DROP TABLE IF EXISTS "FEATURE_1_30";\n\nCREATE TABLE "FEATURE_1_30" AS\nSELECT MEDIAN( t2."tax_paid" ) AS "feature_1_30",\n       t1.rowid AS rownum\nFROM "WEEKLY_SALES_BY_STORE__STAGING_TABLE_1" t1\nINNER JOIN "ORDERS__STAGING_TABLE_2" t2\nON t1."store_id" = t2."store_id"\nWHERE t2."ordered_at" <= t1."reference_date"\nAND ( t2."ordered_at__30_000000_days" > t1."reference_date" OR t2."ordered_at__30_000000_days" IS NULL )\nGROUP BY t1.rowid;                                                                                            |