# Build Snowflake Feature Store with getML

## Prerequisites

```bash
mise env --dotenv > notebooks/.env
```

In [1]:
import getml
from dotenv import load_dotenv

PROJECT_NAME = "snowflake_feature_store"

load_dotenv(dotenv_path=".env")
getml.set_project(PROJECT_NAME)

  Loading pipelines...                     ━━━━━━━━━━━━━━━ 100% • 00:00

Connected to project 'snowflake_feature_store'.

## Setup and Data Loading

In [2]:
import os
from snowflake.snowpark import Session

connection_params: dict[str, str | int] = {
    "account": os.environ["SNOWFLAKE_ACCOUNT"],
    "user": os.environ["SNOWFLAKE_USER"],
    "password": os.environ["SNOWFLAKE_PASSWORD"],
    "role": os.environ["SNOWFLAKE_ROLE"],
    "warehouse": os.environ["SNOWFLAKE_WAREHOUSE"],
    "database": os.environ["SNOWFLAKE_DATABASE"],
    "schema": os.environ["SNOWFLAKE_SCHEMA"],
}

session = Session.builder.configs(connection_params).create()

In [3]:
weekly_sales_by_store = session.table(
    "PREPARED.WEEKLY_SALES_BY_STORE_WITH_TARGET"
).to_arrow()
weekly_sales_by_store = getml.DataFrame.from_arrow(
    weekly_sales_by_store, name="weekly_sales_by_store"
)

orders = session.table("RAW.RAW_ORDERS").to_arrow()
orders = getml.DataFrame.from_arrow(orders, name="orders")

DataFrame.to_arrow() is experimental since 1.28.0. Do not use it in production.
/home/alex/projects/worktrees/getml-demo/60-create-initial-snowflake-notebook-5-sections/integration/snowflake/notebooks/.venv/lib/python3.12/site-packages/getml/data/_io/arrow.py:371: UserWarning:
Column 'NEXT_WEEK_SALES' has been converted from decimal to float. This may
    result in a loss of precision!

  warnings.warn(

## getml Annotations

In [4]:
weekly_sales_by_store.set_role(
    cols=["STORE_ID", "SNAPSHOT_ID"], role=getml.data.roles.join_key
)
weekly_sales_by_store.set_role(cols="REFERENCE_DATE", role=getml.data.roles.time_stamp)
weekly_sales_by_store.set_role(cols="NEXT_WEEK_SALES", role=getml.data.roles.target)
weekly_sales_by_store.set_role(
    cols=[
        "STORE_NAME",
        "YEAR",
        "MONTH",
        "WEEK_NUMBER",
        "IS_FULL_WEEK_AFTER_OPENING",
        "HAS_ORDER_ACTIVITY",
        "HAS_MIN_HISTORY",
    ],
    role=getml.data.roles.categorical,
)
weekly_sales_by_store.set_role(
    cols=["DAYS_SINCE_OPEN", "NEXT_WEEK_ORDERS"], role=getml.data.roles.numerical
)

In [5]:
orders.set_role(cols=["STORE_ID", "ID", "CUSTOMER"], role=getml.data.roles.join_key)
orders.set_role(
    cols="ORDERED_AT",
    role=getml.data.roles.time_stamp,
    time_formats=["%Y-%m-%dT%H:%M:%S"],
)
orders.set_role(
    cols=["SUBTOTAL", "ORDER_TOTAL", "TAX_PAID"], role=getml.data.roles.numerical
)

In [6]:
weekly_sales_by_store

name                REFERENCE_DATE                           STORE_ID   SNAPSHOT_ID   NEXT_WEEK_SALES   ...
role                    time_stamp                           join_key      join_key            target   ...
unit   time stamp, comparison only                                                                      ...
   0                    2019-05-20   fc7707c0-2f1e-48d4-b870-7cbeddfc...            48          13165.49   ...
   1                    2020-04-27   eafbd328-0434-4f46-9c2d-cc97a46f...           145          24888.19   ...
   2                    2020-04-06   eafbd328-0434-4f46-9c2d-cc97a46f...           139          25648.41   ...
   3                    2019-07-08   eafbd328-0434-4f46-9c2d-cc97a46f...            61          10507.1    ...
   4                    2018-12-03   fc7707c0-2f1e-48d4-b870-7cbeddfc...            14           8689.4    ...
                               ...                                ...           ...             ...
1374                    2023-12-11   eafbd328-0434-4f46-9c2d-cc97a46f...          1162          29879.13   ...
1375                    2024-05-27   61743c9b-2394-4d36-8062-8a6820fa...          1302          16341.42   ...
1376                    2024-06-10   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1319          18339.02   ...
1377                    2024-06-10   61743c9b-2394-4d36-8062-8a6820fa...          1314          16471.04   ...
1378                    2024-06-17   61743c9b-2394-4d36-8062-8a6820fa...          1320          14484.91   ...

name   IS_FULL_WEEK_AFTER_OPENING   HAS_ORDER_ACTIVITY   HAS_MIN_HISTORY   DAYS_SINCE_OPEN   NEXT_WEEK_ORDERS
role   categorical                  categorical          categorical             numerical          numerical
unit
   0   true                         true                 true                          261               1126
   1   true                         true                 true                          412               2346
   2   true                         true                 true                          391               2386
   3   true                         true                 true                          118               1113
   4   true                         true                 true                           93                737
       ...                          ...                  ...                           ...                ...
1374   true                         true                 true                         1735               2753
1375   true                         true                 true                          988               1432
1376   true                         true                 true                         2109               1571
1377   true                         true                 true                         1002               1418
1378   true                         true                 true                         1009               1321


1379 rows x 13 columns
memory usage: 0.09 MB
type: getml.DataFrame

In [7]:
orders

   name                    ORDERED_AT                           STORE_ID                                 ID
   role                    time_stamp                           join_key                           join_key
   unit   time stamp, comparison only
      0           2020-05-18 07:44:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   1d78a778-9c83-4092-b185-3e0cb4c8...
      1           2020-05-18 14:01:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   7d8ddf6a-c066-4121-a7fb-10572dcf...
      2           2020-05-18 08:38:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   e664a36d-fcb6-4f6c-8473-b3264209...
      3           2020-05-18 14:43:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   cf5ee75a-68c4-45fe-872a-a7f5b005...
      4           2020-05-18 17:00:00   fc7707c0-2f1e-48d4-b870-7cbeddfc...   0a73b088-99a4-424c-9ace-a9632fc5...
                                  ...                                ...                                ...
2309598           2022-12-05 12:52:00   abfcc332-1eaf-42f6-b8e4-569bf6a3...   0bb3fbbf-bd42-4659-ae80-b28643cf...
2309599           2022-12-05 16:23:00   6964b061-b98d-43f2-9078-ef9c423e...   ea8bcf34-4d67-40e9-9568-3f20523c...
2309600           2022-12-05 08:10:00   6964b061-b98d-43f2-9078-ef9c423e...   06cd30d9-8a92-4d7e-99cc-1ab10ded...
2309601           2022-12-05 12:08:00   6964b061-b98d-43f2-9078-ef9c423e...   5b3c53d1-8568-4848-8f3b-40f627d1...
2309602           2022-12-05 13:02:00   6964b061-b98d-43f2-9078-ef9c423e...   be71238f-cc4e-448f-992b-7cf17d29...

   name                           CUSTOMER    SUBTOTAL   ORDER_TOTAL    TAX_PAID
   role                           join_key   numerical     numerical   numerical
   unit
      0   2d54620c-28bd-44a4-aa0e-5031c01a...         600           636          36
      1   0e0a7730-ba39-48ac-98fd-69293150...         400           424          24
      2   d0ab73cc-8b20-4492-9bd9-ad922bea...         700           742          42
      3   29e77d3b-14bf-4cd4-b4aa-54662ee2...         600           636          36
      4   4c466e98-c2ea-438f-8be4-9669d9e1...        1600          1696          96
                                       ...         ...           ...         ...
2309598   be133bbe-beed-4e26-9844-bc742c3a...         400           425          25
2309599   9b4479a5-0a03-4b2e-81b8-6e5df336...        2100          2257         157
2309600   125a0a24-1681-4658-8beb-980bea15...         500           537          37
2309601   c5667010-0c68-4c80-bd29-fdddd8ef...        2300          2472         172
2309602   64d92869-06cd-4c75-98b7-bd48a9ed...        2400          2579         179


2309603 rows x 7 columns
memory usage: 101.62 MB
type: getml.DataFrame

## getML Data Model

In [8]:
validation_begin = getml.data.time.datetime(2023, 1, 1)
test_begin = getml.data.time.datetime(2024, 1, 1)

split = getml.data.split.time(
    population=weekly_sales_by_store,
    time_stamp="REFERENCE_DATE",
    validation=validation_begin,
    test=test_begin,
)

# Filter dataframes using the split column
weekly_sales_by_store_train = weekly_sales_by_store[split == "train"]
weekly_sales_by_store_validation = weekly_sales_by_store[split == "validation"]
weekly_sales_by_store_test = weekly_sales_by_store[split == "test"]

print(
    f"Training set size: {len(weekly_sales_by_store_train)}"
    f"\nValidation set size: {len(weekly_sales_by_store_validation)}"
    f"\nTest set size: {len(weekly_sales_by_store_test)}"
)

Training set size: 863
Validation set size: 312
Test set size: 204

In [9]:
weekly_sales_by_store_validation

name                REFERENCE_DATE                           STORE_ID   SNAPSHOT_ID   NEXT_WEEK_SALES   ...
role                    time_stamp                           join_key      join_key            target   ...
unit   time stamp, comparison only                                                                      ...
   0                    2023-02-27   abfcc332-1eaf-42f6-b8e4-569bf6a3...           914          24980.54   ...
   1                    2023-05-15   fc7707c0-2f1e-48d4-b870-7cbeddfc...           983          18133.36   ...
   2                    2023-05-22   abfcc332-1eaf-42f6-b8e4-569bf6a3...           986          23574.09   ...
   3                    2023-08-28   fc7707c0-2f1e-48d4-b870-7cbeddfc...          1073          14535.01   ...
   4                    2023-10-23   abfcc332-1eaf-42f6-b8e4-569bf6a3...          1118          26280.78   ...
 ...                           ...                                ...           ...             ...     ...

name   IS_FULL_WEEK_AFTER_OPENING   HAS_ORDER_ACTIVITY   HAS_MIN_HISTORY   DAYS_SINCE_OPEN   NEXT_WEEK_ORDERS
role   categorical                  categorical          categorical             numerical          numerical
unit
   0   true                         true                 true                         1035               2204
   1   true                         true                 true                         1717               1545
   2   true                         true                 true                         1119               2105
   3   true                         true                 true                         1822               1260
   4   true                         true                 true                         1273               2251
 ...   ...                          ...                  ...                           ...                ...


unknown number of rows x 13 columns
type: getml.data.View

In [10]:
data_model = getml.data.DataModel(
    population=weekly_sales_by_store_train.to_placeholder("WEEKLY_SALES_BY_STORE")
)

# Add all peripheral tables
data_model.add(
    getml.data.to_placeholder(
        orders=orders,
    )
)

# Define relationships using joins
data_model.WEEKLY_SALES_BY_STORE.join(
    right=data_model.orders,
    on="STORE_ID",
    time_stamps=("REFERENCE_DATE", "ORDERED_AT"),
    relationship=getml.data.relationship.one_to_many,
    memory=getml.data.time.days(30),
)

In [11]:
container = getml.data.Container(
    train=weekly_sales_by_store_train,
    validation=weekly_sales_by_store_validation,
    test=weekly_sales_by_store_test,
)

# Add peripheral tables with aliases matching the data model placeholders
container.add(
    orders=orders,
)
container.save()
getml.project.data_frames.save()

## Training

In [12]:
fast_prop = getml.feature_learning.FastProp()

predictor = getml.predictors.XGBoostRegressor(
    n_jobs=0,
)

pipe = getml.Pipeline(
    data_model=data_model,
    feature_learners=[
        fast_prop,
    ],
    predictors=[predictor],
)

pipe.fit(container.train)

Checking data model...

  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Checking...                              ━━━━━━━━━━━━━━━ 100% • 00:01

The pipeline check generated 0 issues labeled INFO and 2 issues labeled WARNING.

To see the issues in full, run .check() on the pipeline.

  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:01
  FastProp: Trying 50 features...          ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:03
  XGBoost: Training as predictor...        ━━━━━━━━━━━━━━━ 100% • 00:02

Trained pipeline.

Time taken: 0:00:07.256700.

Pipeline(data_model='WEEKLY_SALES_BY_STORE',
         feature_learners=['FastProp'],
         feature_selectors=[],
         include_categorical=False,
         loss_function='SquareLoss',
         peripheral=['orders'],
         predictors=['XGBoostRegressor'],
         preprocessors=[],
         share_selected_features=0.5,
         tags=['container-tWR94s'])

In [13]:
predictions = pipe.predict(container.test)

# Calculate metrics
scores = pipe.score(container.test)
scores

  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:03
  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:03

    date time             set used   target                  mae        rmse   rsquared
0   2025-12-16 23:45:26   train      NEXT_WEEK_SALES    249.1798    316.897      0.9973
1   2025-12-16 23:45:34   test       NEXT_WEEK_SALES    481.3215    629.0032     0.9856

## Generate getML Feature Interpretations

In [14]:
import getml_interpretations
from getml_interpretations import DomainReport

domain_report: DomainReport = await getml_interpretations.generate_domain_report(
    project_name=PROJECT_NAME,
    pipeline=pipe,
    container=container,
    model="gpt-5.2",
)

  Loading pipelines...                     ━━━━━━━━━━━━━━━ 100% • 00:00

Connected to project 'snowflake_feature_store'.

  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:04
  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:03
  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:03
  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:04
  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:03
  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:03

In [15]:
domain_report.to_markdown()

In [16]:
from pathlib import Path

from getml_interpretations import ColumnDescriptionsReport

jaffle_shop_annotations = Path("annotations.yml")
user_prompt = f"""
Please use the following annotations as source of truth for generating the
column descriptions report:

{jaffle_shop_annotations.read_text()}
"""


column_descriptions_report: ColumnDescriptionsReport = (
    await getml_interpretations.generate_column_descriptions_report(
        project_name=PROJECT_NAME,
        pipeline=pipe,
        container=container,
        domain_report=domain_report,
        model="gpt-5.2",
        user_prompt=user_prompt,
    )
)

In [17]:
column_descriptions_report.to_json()

In [18]:
from getml_interpretations import FeatureDescriptionsReport

feature_descriptions_report: FeatureDescriptionsReport = (
    await getml_interpretations.generate_feature_descriptions_report(
        project_name=PROJECT_NAME,
        pipeline=pipe,
        container=container,
        domain_report=domain_report,
        column_descriptions_report=column_descriptions_report,
        model="gpt-5.2",
        batch_size=20,
    )
)

In [19]:
feature_descriptions_report.to_json()

## Feature Export

In [20]:
import pandas as pd

# Transform features using getML pipeline
features_np = pipe.transform(
    population_table=weekly_sales_by_store,
    peripheral_tables=[orders],
)

# Create DataFrame with meaningful feature names from getML pipeline
features_df = pd.DataFrame(features_np, columns=pipe.features.names)

# Add join keys for Snowflake Feature Store entity linking
features_df["STORE_ID"] = weekly_sales_by_store["STORE_ID"].to_numpy()
features_df["SNAPSHOT_ID"] = weekly_sales_by_store["SNAPSHOT_ID"].to_numpy()

# Uppercase column names to match Snowflake's unquoted identifier convention
features_df.columns = features_df.columns.str.upper()

# Write features to Snowflake table
session.write_pandas(
    df=features_df,
    table_name="GETML_FEATURES",
    schema="GETML_FS",
    auto_create_table=True,
    overwrite=True,
)

  Staging...                               ━━━━━━━━━━━━━━━ 100% • 00:00
  Preprocessing...                         ━━━━━━━━━━━━━━━ 100% • 00:00
  FastProp: Building features...           ━━━━━━━━━━━━━━━ 100% • 00:02

In [21]:
features_df

,FEATURE_1_1,FEATURE_1_2,FEATURE_1_3,FEATURE_1_4,FEATURE_1_5,FEATURE_1_6,FEATURE_1_7,FEATURE_1_8,FEATURE_1_9,FEATURE_1_10,...,FEATURE_1_45,FEATURE_1_46,FEATURE_1_47,FEATURE_1_48,FEATURE_1_49,FEATURE_1_50,DAYS_SINCE_OPEN,NEXT_WEEK_ORDERS,STORE_ID,SNAPSHOT_ID
0,1135.195054,80.0,4611.0,600.0,4300.0,9500.0,600.0,0.0,600.0,1279.079097,...,234000.0,708676.489468,6.034538e+09,0.0,539.309168,4691.0,261.0,1126.0,fc7707c0-2f1e-48d4-b870-7cbeddfc1aac,48
1,1058.410351,89.0,9649.0,1500.0,1800.0,9900.0,600.0,0.0,600.0,1114.206336,...,402720.0,708293.103091,1.269187e+10,0.0,259.903461,9738.0,412.0,2346.0,eafbd328-0434-4f46-9c2d-cc97a46faa13,145
2,1059.729512,84.0,9824.0,400.0,700.0,9900.0,600.0,0.0,600.0,1088.355072,...,1098000.0,707509.957824,1.282615e+10,0.0,255.401231,9908.0,391.0,2386.0,eafbd328-0434-4f46-9c2d-cc97a46faa13,139
3,1018.263736,77.0,4473.0,5100.0,1600.0,9700.0,600.0,0.0,600.0,1162.026676,...,406800.0,710144.524458,6.043895e+09,0.0,555.893603,4550.0,118.0,1113.0,eafbd328-0434-4f46-9c2d-cc97a46faa13,61
4,1169.625247,73.0,2462.0,500.0,1700.0,9300.0,600.0,0.0,600.0,1303.398856,...,406800.0,709068.101433,3.108209e+09,0.0,997.529597,2535.0,93.0,737.0,fc7707c0-2f1e-48d4-b870-7cbeddfc1aac,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1374,1099.489302,88.0,11269.0,400.0,9200.0,9500.0,600.0,0.0,600.0,1156.497623,...,2048400.0,708333.099447,1.462573e+10,0.0,222.844311,11357.0,1735.0,2753.0,eafbd328-0434-4f46-9c2d-cc97a46faa13,1162
1375,1080.277167,78.0,5839.0,600.0,600.0,9600.0,600.0,0.0,600.0,1123.885161,...,2394000.0,711969.715803,7.678430e+09,0.0,427.778905,5917.0,988.0,1432.0,61743c9b-2394-4d36-8062-8a6820fa274a,1302
1376,1143.409056,83.0,6388.0,600.0,700.0,9700.0,600.0,0.0,600.0,1269.610589,...,320400.0,713615.753322,8.410696e+09,0.0,391.085008,6471.0,2109.0,1571.0,fc7707c0-2f1e-48d4-b870-7cbeddfc1aac,1319
1377,1080.887604,82.0,5799.0,1800.0,1100.0,9600.0,600.0,0.0,600.0,1118.385390,...,836400.0,709831.760379,7.672293e+09,0.0,430.295918,5881.0,1002.0,1418.0,61743c9b-2394-4d36-8062-8a6820fa274a,1314
1378,1081.743449,81.0,5758.0,700.0,5600.0,9400.0,600.0,0.0,600.0,1121.648123,...,1441200.0,709950.149926,7.595282e+09,0.0,433.031860,5839.0,1009.0,1321.0,61743c9b-2394-4d36-8062-8a6820fa274a,1320

In [22]:
from snowflake.ml.feature_store import CreationMode, Entity, FeatureStore, FeatureView


# Create Snowpark DataFrame from the table for Feature Store
features_snowpark_df = session.table("GETML_FS.GETML_FEATURES")

# Initialize Feature Store
snowflake_feature_store = FeatureStore(
    session=session,
    database=os.environ["SNOWFLAKE_DATABASE"],
    name="GETML_FS",
    default_warehouse=os.environ["SNOWFLAKE_WAREHOUSE"],
    creation_mode=CreationMode.CREATE_IF_NOT_EXIST,
)

# Create Entity (required for FeatureView)
store_entity = Entity(name="STORE_SNAPSHOT", join_keys=["STORE_ID", "SNAPSHOT_ID"])
snowflake_feature_store.register_entity(store_entity)

/home/alex/projects/worktrees/getml-demo/60-create-initial-snowflake-notebook-5-sections/integration/snowflake/notebooks/.venv/lib/python3.12/site-packages/snowflake/ml/feature_store/feature_store.py:189: UserWarning: Entity STORE_SNAPSHOT already exists. Skip registration.
  return f(self, *args, **kargs)

Entity(name=STORE_SNAPSHOT, join_keys=['STORE_ID', 'SNAPSHOT_ID'], owner=None, desc=)

In [23]:
feature_dict = feature_descriptions_report.model_dump()
feature_dict.get("feature_descriptions")

{'feature_1_1': {'name': 'feature_1_1',
  'title': 'avg_subtotal_last_30d_by_store',
  'description': 'Average order subtotal [currency, pre-tax] for a store over the historical lookback window ending at the store-week reference timestamp.\n\n**How it’s computed (SQL logic)**\n- Join the weekly store-level table to the transactional `orders` table on `STORE_ID` (one-to-many).\n- Keep only transactions with `orders.ORDERED_AT <= weekly_sales_by_store.REFERENCE_DATE` (no future leakage relative to the reference week).\n- Apply a rolling lookback of ~30 days using the generated bound `ORDERED_AT__30_000000_days` (effectively `ORDERED_AT > REFERENCE_DATE - 30 days`).\n- Aggregate `AVG(orders.SUBTOTAL)` across the eligible orders.\n\n**Business meaning**\nRepresents recent average basket value before tax for the store, a proxy for price level / basket composition and recent customer spend behavior.\n\n**Statistical notes**\n- `SUBTOTAL` values are highly discretized (few price points overall), so the mean tends to move mainly with shifts in mix/volume of those price points rather than continuous pricing.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Very weak linear relationship in this training run (correlation ≈ -0.01; low model importance vs volume-driven features). This suggests next-week sales are driven more by order count/run-rate than by changes in average basket size.\n\n**Usage guidance**\n- Useful as an “AOV-like” control feature; consider combining with order counts to form a cleaner KPI: `SUM(order_total)/COUNT(orders)`.\n- Monitor for drift if pricing/menu changes occur; otherwise expect limited incremental lift when strong volume features (e.g., next-week orders) are present.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_2': {'name': 'feature_1_2',
  'title': 'distinct_subtotal_values_last_30d_by_store',
  'description': 'Count of distinct subtotal amounts observed [count] in a store’s orders during the ~30-day lookback window ending at the store-week reference timestamp.\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` → `orders` on `STORE_ID`.\n- Filter to orders with `ORDERED_AT <= REFERENCE_DATE`.\n- Restrict to the last ~30 days via the lookback boundary (`ORDERED_AT > REFERENCE_DATE - 30 days`).\n- Compute `COUNT(DISTINCT orders.SUBTOTAL)`.\n\n**Business meaning**\nActs as a crude proxy for recent variety in basket totals (and indirectly product/bundle mix) at the store.\n\n**Statistical notes**\n- Because `SUBTOTAL` has very few distinct price points overall (discretized pricing), this feature often behaves more like a bounded “variety counter” than a true diversity measure.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Moderate positive correlation (≈ 0.24) but very low importance in this model, likely because it is redundant with stronger demand/run-rate features.\n\n**Usage guidance**\n- Prefer more interpretable mix/variety features if available (e.g., distinct customers, distinct SKUs, or order-size buckets).\n- If kept, treat as a stability/mix indicator rather than a direct sales driver.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_3': {'name': 'feature_1_3',
  'title': 'duplicate_subtotal_count_last_30d_by_store',
  'description': 'Number of “non-unique” subtotal occurrences [count] for a store in the ~30-day lookback window, computed as total subtotal records minus distinct subtotal values.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID` between weekly store rows and `orders`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within the prior ~30 days.\n- Compute: `COUNT(orders.SUBTOTAL) - COUNT(DISTINCT orders.SUBTOTAL)`.\n\n**Business meaning**\nMeasures how repetitive the store’s order subtotals are in the recent window. With discretized pricing, higher values largely indicate higher transaction volume and/or a strong concentration in common basket totals.\n\n**Statistical notes**\n- This is strongly tied to order volume because as counts grow faster than distinct subtotals, the difference increases.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Very high correlation (≈ 0.97) but low model importance in the current run, consistent with redundancy once other volume proxies (and especially `NEXT_WEEK_ORDERS`) are present.\n\n**Usage guidance**\n- Interpretable as a proxy for recent throughput when explicit order counts are not available.\n- If you already include order counts/sums, consider dropping to reduce multicollinearity.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_4': {'name': 'feature_1_4',
  'title': 'earliest_subtotal_last_30d_by_store',
  'description': 'Subtotal amount [currency, pre-tax] of the earliest order within the ~30-day lookback window for the store (i.e., the order farthest back in time but still within the window).\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` to `orders` on `STORE_ID`.\n- Keep orders with `ORDERED_AT <= REFERENCE_DATE` and within the prior ~30 days.\n- Use `FIRST(orders.SUBTOTAL, orders.ORDERED_AT)` to pick the subtotal associated with the minimum `ORDERED_AT` in the window.\n\n**Business meaning**\nA single-point snapshot of basket size at the start of the lookback period; can weakly reflect mix/price level at the beginning of the month.\n\n**Statistical notes**\n- As a single observation, it is noisy and sensitive to outliers and low-order-count periods.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Weak relationship (correlation ≈ -0.04; very low importance).\n\n**Usage guidance**\n- Typically less stable than aggregated measures (mean/sum). Prefer window aggregates (avg/sum) or quantiles if you need distribution shape.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_5': {'name': 'feature_1_5',
  'title': 'latest_subtotal_last_30d_by_store',
  'description': 'Subtotal amount [currency, pre-tax] of the most recent order within the ~30-day lookback window for the store (closest to the reference timestamp).\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter orders to those on/before `REFERENCE_DATE` and within ~30 days.\n- Use `LAST(orders.SUBTOTAL, orders.ORDERED_AT)` to pick the subtotal tied to the maximum `ORDERED_AT` in the window.\n\n**Business meaning**\nCaptures the basket size of the latest transaction observed before the store-week reference point—an ultra-recent signal of current basket behavior.\n\n**Statistical notes**\n- Highly sensitive to last observed order (noise), especially in low-volume stores/weeks.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Mild negative correlation (≈ -0.24) and negligible importance in this run; likely not a stable driver once volume/run-rate is modeled.\n\n**Usage guidance**\n- More useful as a freshness indicator when combined with recency/cadence features; otherwise consider replacing with rolling medians/percentiles.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_6': {'name': 'feature_1_6',
  'title': 'max_subtotal_last_30d_by_store',
  'description': 'Maximum order subtotal observed [currency, pre-tax] for the store in the ~30-day lookback window ending at the reference date.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Aggregate `MAX(orders.SUBTOTAL)`.\n\n**Business meaning**\nRepresents the largest basket (pre-tax) seen recently—proxy for presence of large/catering orders or occasional high-spend events.\n\n**Statistical notes**\n- `SUBTOTAL` overall ranges up to ~10,100, so maxima can reflect rare outliers.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Weak negative correlation (≈ -0.09) and very low importance; maxima are noisy and not consistently predictive of next-week totals in this setup.\n\n**Usage guidance**\n- Useful for risk/ops planning (capacity for unusually large orders) more than for baseline forecasting.\n- Consider winsorizing or using upper quantiles (p90/p95) for robustness.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_7': {'name': 'feature_1_7',
  'title': 'median_subtotal_last_30d_by_store',
  'description': 'Median order subtotal [currency, pre-tax] for the store over the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders with `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Compute `MEDIAN(orders.SUBTOTAL)`.\n\n**Business meaning**\nA robust “typical basket size” measure, less sensitive to large outlier orders than the mean.\n\n**Statistical notes**\n- With strongly discretized subtotal values, the median may frequently equal a common price point and can be nearly constant for some stores/time periods.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- In this run it provides no incremental lift (importance 0; correlation reported 0), consistent with being near-constant and/or dominated by volume predictors.\n\n**Usage guidance**\n- Keep if you remove forward-looking/strong volume features and want a stable basket-size component; otherwise it can be redundant.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_8': {'name': 'feature_1_8',
  'title': 'min_subtotal_last_30d_by_store',
  'description': 'Minimum order subtotal observed [currency, pre-tax] for the store in the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join weekly store rows to `orders` on `STORE_ID`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within the prior ~30 days.\n- Aggregate `MIN(orders.SUBTOTAL)`.\n\n**Business meaning**\nCaptures the smallest basket size recently; can indicate the presence of very small transactions, refunds/zero subtotals, or minimum-price items.\n\n**Statistical notes**\n- Since subtotals can be 0, the minimum may be 0 for many windows, making it low-signal.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- No apparent predictive value here (importance 0; correlation 0), likely due to saturation at 0.\n\n**Usage guidance**\n- Primarily a data-quality/anomaly feature (e.g., unexpected zeros). Consider excluding from the model if it’s mostly constant.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_9': {'name': 'feature_1_9',
  'title': 'mode_subtotal_last_30d_by_store',
  'description': 'Most frequent (modal) subtotal amount [currency, pre-tax] for the store in the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders on/before `REFERENCE_DATE` and within ~30 days.\n- Compute `MODE(orders.SUBTOTAL)`.\n\n**Business meaning**\nRepresents the most common basket total—often corresponds to the dominant bundle/price point at the store.\n\n**Statistical notes**\n- With discretized pricing, the mode can be very stable and thus provide limited variation.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- No incremental predictive value in this run (importance 0; correlation 0), consistent with near-constant behavior.\n\n**Usage guidance**\n- Useful for merchandising/operations insights (dominant order type) more than forecasting; consider using mix shares (e.g., fraction of orders at the modal price point) if you want a stronger signal.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_10': {'name': 'feature_1_10',
  'title': 'stddev_subtotal_last_30d_by_store',
  'description': 'Standard deviation of order subtotals [currency, pre-tax] for the store within the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` to `orders` by `STORE_ID`.\n- Filter to orders `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Aggregate `STDDEV(orders.SUBTOTAL)`.\n\n**Business meaning**\nMeasures variability in basket sizes—proxy for how mixed the store’s order sizes are (e.g., combination of small and large orders).\n\n**Statistical notes**\n- Variability can increase with a mix of order types; however, when pricing is discretized it may reflect mix shifts between a few common price points.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Moderate-to-strong negative correlation (≈ -0.53) but very low importance, suggesting it is not a causal driver and/or is redundant/confounded with store maturity or volume.\n\n**Usage guidance**\n- Consider pairing with volume features to separate “more orders” from “more heterogeneous orders.”\n- If used operationally, higher variability may imply more complex staffing/prep needs.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_11': {'name': 'feature_1_11',
  'title': 'sum_subtotal_last_30d_by_store',
  'description': 'Total pre-tax revenue run-rate [currency, pre-tax] for the store over the ~30-day lookback window ending at the reference date.\n\n**How it’s computed (SQL logic)**\n- Join store-week records to `orders` on `STORE_ID`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within the prior ~30 days.\n- Aggregate `SUM(orders.SUBTOTAL)`.\n\n**Business meaning**\nA primary demand/run-rate indicator: how much the store sold (pre-tax) recently. This often captures baseline momentum that carries into the next week.\n\n**Statistical notes**\n- With high transaction volume, sums are typically stable and strongly related to near-future sales.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Very strong correlation (≈ 0.97) and meaningful importance (~0.011), making it one of the strongest historical-order-derived predictors (though still far smaller than `NEXT_WEEK_ORDERS` in this run).\n\n**Usage guidance**\n- Highly recommended for “planning mode” forecasts when future orders are unknown.\n- Combine with order count in-window to derive AOV and separate volume vs basket-size effects.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_12': {'name': 'feature_1_12',
  'title': 'trend_subtotal_vs_recency_last_30d_by_store',
  'description': 'Trend of order subtotal as a function of recency [currency/day or currency per unit time-difference], estimated over orders in the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders on/before `REFERENCE_DATE` and within ~30 days.\n- Compute `TREND(orders.SUBTOTAL, REFERENCE_DATE - orders.ORDERED_AT)`, where the second argument is the time difference (larger values = older orders).\n\n**Business meaning**\nApproximates whether basket sizes were larger or smaller earlier in the lookback window compared with more recent orders—i.e., short-term directional change in basket value.\n\n**Statistical notes**\n- This is a derived slope-like statistic and can be noisy with few orders or discretized subtotals.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Near-zero correlation (≈ -0.00) and small importance, indicating limited incremental signal here.\n\n**Usage guidance**\n- More informative when calculated over multiple horizons (7/30/90 days) or after removing strong leakage-like predictors.\n- Interpret carefully: sign depends on the chosen time-difference encoding (older vs newer).',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_13': {'name': 'feature_1_13',
  'title': 'avg_order_total_last_30d_by_store',
  'description': 'Average order total [currency, post-tax] for a store over the ~30-day lookback window ending at the weekly reference date.\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` to `orders` using `STORE_ID`.\n- Include orders with `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Aggregate `AVG(orders.ORDER_TOTAL)`.\n\n**Business meaning**\nRepresents recent average revenue per order including tax (AOV including tax). Useful for capturing changes in pricing, basket size, or tax/fee treatment.\n\n**Statistical notes**\n- `ORDER_TOTAL` is also discretized with limited distinct values; mean changes are primarily mix-driven.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Weak negative correlation (≈ -0.11) and low importance, consistent with the domain insight that next-week sales are mostly volume-driven rather than AOV-driven.\n\n**Usage guidance**\n- Keep as a guardrail for price/mix shifts, especially if you remove `NEXT_WEEK_ORDERS`.\n- Consider normalizing by pre-tax subtotal to estimate effective tax/fee rate if that can vary.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_14': {'name': 'feature_1_14',
  'title': 'distinct_order_total_values_last_30d_by_store',
  'description': 'Count of distinct order total amounts [count] observed in the store’s orders during the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders on/before `REFERENCE_DATE` and within ~30 days.\n- Compute `COUNT(DISTINCT orders.ORDER_TOTAL)`.\n\n**Business meaning**\nA bounded proxy for variety of charged totals (potentially reflecting different bundles/discounts) in recent transactions.\n\n**Statistical notes**\n- With discretized totals, this count may track volume/mix breadth more than true price variability.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Moderate correlation (≈ 0.24) but zero measured importance, likely redundant given other volume/run-rate signals.\n\n**Usage guidance**\n- Prefer distinct-customer counts or item-level diversity if available; use this mainly for mix monitoring.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_15': {'name': 'feature_1_15',
  'title': 'duplicate_order_total_count_last_30d_by_store',
  'description': 'Number of “non-unique” order total occurrences [count] in the ~30-day window, computed as total order_total records minus distinct order_total values.\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` to `orders` on `STORE_ID`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Compute: `COUNT(orders.ORDER_TOTAL) - COUNT(DISTINCT orders.ORDER_TOTAL)`.\n\n**Business meaning**\nCaptures how repetitive order totals are; in a discretized pricing environment this becomes a strong proxy for transaction volume.\n\n**Statistical notes**\n- Strongly increases with the number of orders in the window, because distinct totals saturate while counts keep growing.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Very high correlation (≈ 0.97) but no incremental importance here, consistent with redundancy when better volume proxies exist.\n\n**Usage guidance**\n- Can stand in for recent order volume if explicit counts are missing; otherwise consider removing to reduce redundancy.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_16': {'name': 'feature_1_16',
  'title': 'earliest_order_total_last_30d_by_store',
  'description': 'Order total [currency, post-tax] from the earliest order within the ~30-day lookback window for the store.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders on/before `REFERENCE_DATE` and within ~30 days.\n- Use `FIRST(orders.ORDER_TOTAL, orders.ORDERED_AT)` to select the order total at the minimum order timestamp in the window.\n\n**Business meaning**\nA single snapshot of charged amount at the start of the month-like window; may reflect initial mix/pricing within the period.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Weak negative correlation (≈ -0.04) and extremely small importance, indicating low incremental predictive value.\n\n**Usage guidance**\n- Prefer aggregates (sum/avg) over single-order statistics for forecasting; keep mainly if modeling abrupt mix shifts where the first/last observations matter.',
  'description_confidence': <Confidence.HIGH: 'high'>},
 'feature_1_17': {'name': 'feature_1_17',
  'title': 'latest_order_total_last_30d_by_store',

In [25]:
# Create external FeatureView (refresh_freq=None means externally managed)
weekly_sales_feature_view = FeatureView(
    name="weekly_sales_features",
    entities=[store_entity],
    feature_df=features_snowpark_df,
    refresh_freq=None,
    desc="Features generated by getML for weekly sales prediction",
)

# Build feature descriptions with uppercase keys to match Snowflake column names
# Extract description strings from nested dicts and uppercase the keys
feature_descs = feature_dict.get("feature_descriptions", {})
feature_descs_upper = {
    k.upper(): v.get("description", "") if isinstance(v, dict) else v
    for k, v in feature_descs.items()
}

weekly_sales_feature_view = weekly_sales_feature_view.attach_feature_desc(
    feature_descs_upper
)

# Register the FeatureView
registered_feature_view = snowflake_feature_store.register_feature_view(
    feature_view=weekly_sales_feature_view, version="1", overwrite=True
)

registered_feature_view

FeatureView(_name=WEEKLY_SALES_FEATURES, _entities=[Entity(name=STORE_SNAPSHOT, join_keys=['STORE_ID', 'SNAPSHOT_ID'], owner=None, desc=)], _feature_df=<snowflake.snowpark.dataframe.DataFrame object at 0x736191371c40>, _timestamp_col=None, _desc=Features generated by getML for weekly sales prediction, _infer_schema_df=<snowflake.snowpark.dataframe.DataFrame object at 0x7361912ff560>, _query=SELECT  *  FROM GETML_FS.GETML_FEATURES, _version=1, _status=FeatureViewStatus.STATIC, _feature_desc=OrderedDict({'FEATURE_1_1': 'Average order subtotal [currency, pre-tax] for a store over the historical lookback window ending at the store-week reference timestamp.\n\n**How it’s computed (SQL logic)**\n- Join the weekly store-level table to the transactional `orders` table on `STORE_ID` (one-to-many).\n- Keep only transactions with `orders.ORDERED_AT <= weekly_sales_by_store.REFERENCE_DATE` (no future leakage relative to the reference week).\n- Apply a rolling lookback of ~30 days using the generated bound `ORDERED_AT__30_000000_days` (effectively `ORDERED_AT > REFERENCE_DATE - 30 days`).\n- Aggregate `AVG(orders.SUBTOTAL)` across the eligible orders.\n\n**Business meaning**\nRepresents recent average basket value before tax for the store, a proxy for price level / basket composition and recent customer spend behavior.\n\n**Statistical notes**\n- `SUBTOTAL` values are highly discretized (few price points overall), so the mean tends to move mainly with shifts in mix/volume of those price points rather than continuous pricing.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Very weak linear relationship in this training run (correlation ≈ -0.01; low model importance vs volume-driven features). This suggests next-week sales are driven more by order count/run-rate than by changes in average basket size.\n\n**Usage guidance**\n- Useful as an “AOV-like” control feature; consider combining with order counts to form a cleaner KPI: `SUM(order_total)/COUNT(orders)`.\n- Monitor for drift if pricing/menu changes occur; otherwise expect limited incremental lift when strong volume features (e.g., next-week orders) are present.', 'FEATURE_1_2': 'Count of distinct subtotal amounts observed [count] in a store’s orders during the ~30-day lookback window ending at the store-week reference timestamp.\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` → `orders` on `STORE_ID`.\n- Filter to orders with `ORDERED_AT <= REFERENCE_DATE`.\n- Restrict to the last ~30 days via the lookback boundary (`ORDERED_AT > REFERENCE_DATE - 30 days`).\n- Compute `COUNT(DISTINCT orders.SUBTOTAL)`.\n\n**Business meaning**\nActs as a crude proxy for recent variety in basket totals (and indirectly product/bundle mix) at the store.\n\n**Statistical notes**\n- Because `SUBTOTAL` has very few distinct price points overall (discretized pricing), this feature often behaves more like a bounded “variety counter” than a true diversity measure.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Moderate positive correlation (≈ 0.24) but very low importance in this model, likely because it is redundant with stronger demand/run-rate features.\n\n**Usage guidance**\n- Prefer more interpretable mix/variety features if available (e.g., distinct customers, distinct SKUs, or order-size buckets).\n- If kept, treat as a stability/mix indicator rather than a direct sales driver.', 'FEATURE_1_3': 'Number of “non-unique” subtotal occurrences [count] for a store in the ~30-day lookback window, computed as total subtotal records minus distinct subtotal values.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID` between weekly store rows and `orders`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within the prior ~30 days.\n- Compute: `COUNT(orders.SUBTOTAL) - COUNT(DISTINCT orders.SUBTOTAL)`.\n\n**Business meaning**\nMeasures how repetitive the store’s order subtotals are in the recent window. With discretized pricing, higher values largely indicate higher transaction volume and/or a strong concentration in common basket totals.\n\n**Statistical notes**\n- This is strongly tied to order volume because as counts grow faster than distinct subtotals, the difference increases.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Very high correlation (≈ 0.97) but low model importance in the current run, consistent with redundancy once other volume proxies (and especially `NEXT_WEEK_ORDERS`) are present.\n\n**Usage guidance**\n- Interpretable as a proxy for recent throughput when explicit order counts are not available.\n- If you already include order counts/sums, consider dropping to reduce multicollinearity.', 'FEATURE_1_4': 'Subtotal amount [currency, pre-tax] of the earliest order within the ~30-day lookback window for the store (i.e., the order farthest back in time but still within the window).\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` to `orders` on `STORE_ID`.\n- Keep orders with `ORDERED_AT <= REFERENCE_DATE` and within the prior ~30 days.\n- Use `FIRST(orders.SUBTOTAL, orders.ORDERED_AT)` to pick the subtotal associated with the minimum `ORDERED_AT` in the window.\n\n**Business meaning**\nA single-point snapshot of basket size at the start of the lookback period; can weakly reflect mix/price level at the beginning of the month.\n\n**Statistical notes**\n- As a single observation, it is noisy and sensitive to outliers and low-order-count periods.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Weak relationship (correlation ≈ -0.04; very low importance).\n\n**Usage guidance**\n- Typically less stable than aggregated measures (mean/sum). Prefer window aggregates (avg/sum) or quantiles if you need distribution shape.', 'FEATURE_1_5': 'Subtotal amount [currency, pre-tax] of the most recent order within the ~30-day lookback window for the store (closest to the reference timestamp).\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter orders to those on/before `REFERENCE_DATE` and within ~30 days.\n- Use `LAST(orders.SUBTOTAL, orders.ORDERED_AT)` to pick the subtotal tied to the maximum `ORDERED_AT` in the window.\n\n**Business meaning**\nCaptures the basket size of the latest transaction observed before the store-week reference point—an ultra-recent signal of current basket behavior.\n\n**Statistical notes**\n- Highly sensitive to last observed order (noise), especially in low-volume stores/weeks.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Mild negative correlation (≈ -0.24) and negligible importance in this run; likely not a stable driver once volume/run-rate is modeled.\n\n**Usage guidance**\n- More useful as a freshness indicator when combined with recency/cadence features; otherwise consider replacing with rolling medians/percentiles.', 'FEATURE_1_6': 'Maximum order subtotal observed [currency, pre-tax] for the store in the ~30-day lookback window ending at the reference date.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Aggregate `MAX(orders.SUBTOTAL)`.\n\n**Business meaning**\nRepresents the largest basket (pre-tax) seen recently—proxy for presence of large/catering orders or occasional high-spend events.\n\n**Statistical notes**\n- `SUBTOTAL` overall ranges up to ~10,100, so maxima can reflect rare outliers.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Weak negative correlation (≈ -0.09) and very low importance; maxima are noisy and not consistently predictive of next-week totals in this setup.\n\n**Usage guidance**\n- Useful for risk/ops planning (capacity for unusually large orders) more than for baseline forecasting.\n- Consider winsorizing or using upper quantiles (p90/p95) for robustness.', 'FEATURE_1_7': 'Median order subtotal [currency, pre-tax] for the store over the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders with `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Compute `MEDIAN(orders.SUBTOTAL)`.\n\n**Business meaning**\nA robust “typical basket size” measure, less sensitive to large outlier orders than the mean.\n\n**Statistical notes**\n- With strongly discretized subtotal values, the median may frequently equal a common price point and can be nearly constant for some stores/time periods.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- In this run it provides no incremental lift (importance 0; correlation reported 0), consistent with being near-constant and/or dominated by volume predictors.\n\n**Usage guidance**\n- Keep if you remove forward-looking/strong volume features and want a stable basket-size component; otherwise it can be redundant.', 'FEATURE_1_8': 'Minimum order subtotal observed [currency, pre-tax] for the store in the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join weekly store rows to `orders` on `STORE_ID`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within the prior ~30 days.\n- Aggregate `MIN(orders.SUBTOTAL)`.\n\n**Business meaning**\nCaptures the smallest basket size recently; can indicate the presence of very small transactions, refunds/zero subtotals, or minimum-price items.\n\n**Statistical notes**\n- Since subtotals can be 0, the minimum may be 0 for many windows, making it low-signal.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- No apparent predictive value here (importance 0; correlation 0), likely due to saturation at 0.\n\n**Usage guidance**\n- Primarily a data-quality/anomaly feature (e.g., unexpected zeros). Consider excluding from the model if it’s mostly constant.', 'FEATURE_1_9': 'Most frequent (modal) subtotal amount [currency, pre-tax] for the store in the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders on/before `REFERENCE_DATE` and within ~30 days.\n- Compute `MODE(orders.SUBTOTAL)`.\n\n**Business meaning**\nRepresents the most common basket total—often corresponds to the dominant bundle/price point at the store.\n\n**Statistical notes**\n- With discretized pricing, the mode can be very stable and thus provide limited variation.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- No incremental predictive value in this run (importance 0; correlation 0), consistent with near-constant behavior.\n\n**Usage guidance**\n- Useful for merchandising/operations insights (dominant order type) more than forecasting; consider using mix shares (e.g., fraction of orders at the modal price point) if you want a stronger signal.', 'FEATURE_1_10': 'Standard deviation of order subtotals [currency, pre-tax] for the store within the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` to `orders` by `STORE_ID`.\n- Filter to orders `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Aggregate `STDDEV(orders.SUBTOTAL)`.\n\n**Business meaning**\nMeasures variability in basket sizes—proxy for how mixed the store’s order sizes are (e.g., combination of small and large orders).\n\n**Statistical notes**\n- Variability can increase with a mix of order types; however, when pricing is discretized it may reflect mix shifts between a few common price points.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Moderate-to-strong negative correlation (≈ -0.53) but very low importance, suggesting it is not a causal driver and/or is redundant/confounded with store maturity or volume.\n\n**Usage guidance**\n- Consider pairing with volume features to separate “more orders” from “more heterogeneous orders.”\n- If used operationally, higher variability may imply more complex staffing/prep needs.', 'FEATURE_1_11': 'Total pre-tax revenue run-rate [currency, pre-tax] for the store over the ~30-day lookback window ending at the reference date.\n\n**How it’s computed (SQL logic)**\n- Join store-week records to `orders` on `STORE_ID`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within the prior ~30 days.\n- Aggregate `SUM(orders.SUBTOTAL)`.\n\n**Business meaning**\nA primary demand/run-rate indicator: how much the store sold (pre-tax) recently. This often captures baseline momentum that carries into the next week.\n\n**Statistical notes**\n- With high transaction volume, sums are typically stable and strongly related to near-future sales.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Very strong correlation (≈ 0.97) and meaningful importance (~0.011), making it one of the strongest historical-order-derived predictors (though still far smaller than `NEXT_WEEK_ORDERS` in this run).\n\n**Usage guidance**\n- Highly recommended for “planning mode” forecasts when future orders are unknown.\n- Combine with order count in-window to derive AOV and separate volume vs basket-size effects.', 'FEATURE_1_12': 'Trend of order subtotal as a function of recency [currency/day or currency per unit time-difference], estimated over orders in the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders on/before `REFERENCE_DATE` and within ~30 days.\n- Compute `TREND(orders.SUBTOTAL, REFERENCE_DATE - orders.ORDERED_AT)`, where the second argument is the time difference (larger values = older orders).\n\n**Business meaning**\nApproximates whether basket sizes were larger or smaller earlier in the lookback window compared with more recent orders—i.e., short-term directional change in basket value.\n\n**Statistical notes**\n- This is a derived slope-like statistic and can be noisy with few orders or discretized subtotals.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Near-zero correlation (≈ -0.00) and small importance, indicating limited incremental signal here.\n\n**Usage guidance**\n- More informative when calculated over multiple horizons (7/30/90 days) or after removing strong leakage-like predictors.\n- Interpret carefully: sign depends on the chosen time-difference encoding (older vs newer).', 'FEATURE_1_13': 'Average order total [currency, post-tax] for a store over the ~30-day lookback window ending at the weekly reference date.\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` to `orders` using `STORE_ID`.\n- Include orders with `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Aggregate `AVG(orders.ORDER_TOTAL)`.\n\n**Business meaning**\nRepresents recent average revenue per order including tax (AOV including tax). Useful for capturing changes in pricing, basket size, or tax/fee treatment.\n\n**Statistical notes**\n- `ORDER_TOTAL` is also discretized with limited distinct values; mean changes are primarily mix-driven.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Weak negative correlation (≈ -0.11) and low importance, consistent with the domain insight that next-week sales are mostly volume-driven rather than AOV-driven.\n\n**Usage guidance**\n- Keep as a guardrail for price/mix shifts, especially if you remove `NEXT_WEEK_ORDERS`.\n- Consider normalizing by pre-tax subtotal to estimate effective tax/fee rate if that can vary.', 'FEATURE_1_14': 'Count of distinct order total amounts [count] observed in the store’s orders during the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders on/before `REFERENCE_DATE` and within ~30 days.\n- Compute `COUNT(DISTINCT orders.ORDER_TOTAL)`.\n\n**Business meaning**\nA bounded proxy for variety of charged totals (potentially reflecting different bundles/discounts) in recent transactions.\n\n**Statistical notes**\n- With discretized totals, this count may track volume/mix breadth more than true price variability.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Moderate correlation (≈ 0.24) but zero measured importance, likely redundant given other volume/run-rate signals.\n\n**Usage guidance**\n- Prefer distinct-customer counts or item-level diversity if available; use this mainly for mix monitoring.', 'FEATURE_1_15': 'Number of “non-unique” order total occurrences [count] in the ~30-day window, computed as total order_total records minus distinct order_total values.\n\n**How it’s computed (SQL logic)**\n- Join `weekly_sales_by_store` to `orders` on `STORE_ID`.\n- Filter to `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Compute: `COUNT(orders.ORDER_TOTAL) - COUNT(DISTINCT orders.ORDER_TOTAL)`.\n\n**Business meaning**\nCaptures how repetitive order totals are; in a discretized pricing environment this becomes a strong proxy for transaction volume.\n\n**Statistical notes**\n- Strongly increases with the number of orders in the window, because distinct totals saturate while counts keep growing.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Very high correlation (≈ 0.97) but no incremental importance here, consistent with redundancy when better volume proxies exist.\n\n**Usage guidance**\n- Can stand in for recent order volume if explicit counts are missing; otherwise consider removing to reduce redundancy.', 'FEATURE_1_16': 'Order total [currency, post-tax] from the earliest order within the ~30-day lookback window for the store.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders on/before `REFERENCE_DATE` and within ~30 days.\n- Use `FIRST(orders.ORDER_TOTAL, orders.ORDERED_AT)` to select the order total at the minimum order timestamp in the window.\n\n**Business meaning**\nA single snapshot of charged amount at the start of the month-like window; may reflect initial mix/pricing within the period.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Weak negative correlation (≈ -0.04) and extremely small importance, indicating low incremental predictive value.\n\n**Usage guidance**\n- Prefer aggregates (sum/avg) over single-order statistics for forecasting; keep mainly if modeling abrupt mix shifts where the first/last observations matter.', 'FEATURE_1_17': 'Order total [currency, post-tax] from the most recent order within the ~30-day lookback window for the store.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to orders `ORDERED_AT <= REFERENCE_DATE` and within ~30 days.\n- Use `LAST(orders.ORDER_TOTAL, orders.ORDERED_AT)` to select the order total at the maximum order timestamp in the window.\n\n**Business meaning**\nUltra-recent snapshot of charged amount; may capture last-minute promotions, large orders, or current basket tendencies.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Mild negative correlation (≈ -0.24) and very low importance.\n\n**Usage guidance**\n- Noisy by design; use with caution or replace with recent-window quantiles/rolling averages for stability.', 'FEATURE_1_18': 'Maximum order total [currency, post-tax] observed for the store in the ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join weekly store rows to `orders` via `STORE_ID`.\n- Filter to orders on/before `REFERENCE_DATE` and within ~30 days.\n- Aggregate `MAX(orders.ORDER_TOTAL)`.\n\n**Business meaning**\nRepresents the largest charged transaction recently; proxy for big-ticket orders (e.g., catering) that can create spikes.\n\n**Statistical notes**\n- Maxima can be dominated by rare events and are less stable than sums.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Weak negative correlation (≈ -0.25) and very low importance.\n\n**Usage guidance**\n- More useful for operational planning/outlier detection than core forecasting; consider robust alternatives (p95).', 'FEATURE_1_19': 'Median order total [currency, post-tax] within the store’s ~30-day lookback window.\n\n**How it’s computed (SQL logic)**\n- Join on `STORE_ID`.\n- Filter to eligible orders (<= `REFERENCE_DATE` and within ~30 days).\n- Compute `MEDIAN(orders.ORDER_TOTAL)`.\n\n**Business meaning**\nRobust typical charged amount per order; less sensitive to occasional very large orders.\n\n**Relationship to target (NEXT_WEEK_SALES)**\n- Negative correlation (≈ -0.25) and zero importance in this run, likely due to limited variation and dominance of volume predictors.\n\n**Usage guidance**\n- Useful if you decompose sales into o

https://app.snowflake.com/pgciadt/sm09519/#/features/database/JAFFLE_SHOP/store/GETML_FS/feature-view/WEEKLY_SALES_FEATURES/version/1/feature-view-details